baseurl = "https://eclipse.dev/kura"
DefaultContentLanguage = "en"
title = "Eclipse Kura"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = ["taxonomy", "term"]
themesDir = "node_modules/"
enableRobotsTXT = true
pluralizeListTitles = false
disablePathToLower = true

[Params]
  #google_tag_manager = "GTM-5WLCZXC"
  description = "Eclipse Kura™ is a versatile framework to supercharge your edge devices, streamlining the process of configuring your gateway, connecting sensors, and IoT devices to seamlessly collect, process, and send data to the cloud."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = [
    "Kura", "Gateway", "java",
    "Internet-of-things", "Open Source", "IoT", "Permissive License",
    "Gateway Software Solutions", "Gateway Systems Development", "IoT Framework", "Industry 4.0",
    "Edge Development", "Edge AI"
  ]
  news_count = 3
  featured_content_publish_target = "eclipse_org"
  styles = "public/css/styles.css"
  gcse = "011805775785170369411:p3ec0igo0qq"
  gcse_result_url = "/home/search/"
  # eclipse_search_icon = "<i data-feather=\"search\" stroke-width=\"1\"></i>"
  js = "public/js/main.js?v1.0"
  header_wrapper_class = "header-wrapper"
  call_for_action_text = "Download"
  call_for_action_url = "/downloads/"
  share_img = "/images/social-media.jpg"
  favicon = "/favicon.ico"
  logo = "/images/kura.png"
  logo_width = "160"
  layout_style = "astro"
  hide_ad = false
  hide_call_for_action = true
  jumbotron_class = "col-xs-24"

#  logo_width = ""
#  header_left_classes = ""
#  main_menu_wrapper_classes = "col-sm-17 margin-top-25"
#  projects_working_group = ""
#  show_events = true
#  table_classes = "table table-bordered"
#  hide_cfa_same_page = true
#  show_collapsible_menu = true
  sidebar_layout = "default"

[taxonomies]
  tag = "tags"

[params.author]
  name = "Eclipse Foundation"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "eclipsefdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
  name = "Downloads"
  url = "https://github.com/eclipse-kura/kura/releases"
  weight = 1

[[menu.main]]
  name = "Documentation"
  url = "http://eclipse-kura.github.io/kura/"
  weight = 2

[[menu.main]]
  name = "Community"
  url = "https://github.com/eclipse-kura/kura/discussions"
  weight = 3

[[menu.main]]
  name = "Marketplace"
  url = "https://marketplace.eclipse.org/taxonomy/term/4397%2C4396/title"
  weight = 4
