
[[main]]
    name = "Examples"
    url = "#"
    weight = 2
    identifier = "examples"

[[main]]
    name = "Single Page"
    url = "/single_page/"
    weight = 1
    parent = "examples"

[[main]]
    name = "News sample"
    url = "/news/"
    weight = 2
    parent = "examples"

[[main]]
    name = "Membership sample"
    url = "/membership/"
    weight = 3
    parent = "examples"

[[main]]
    name = "Events sample"
    url = "/events/"
    weight = 3
    parent = "examples"

[[main]]
    name = "FAQ sample"
    url = "/faq/"
    weight = 4
    parent = "examples"

[[main]]
    name = "Hide Call For Action"
    url = "/hide_call_for_action/"
    weight = 5
    parent = "examples"

[[main]]
    name = "Without Breadcrumb"
    url = "/without_breadcrumb/"
    weight = 6
    parent = "examples"

[[main]]
    name = "multi-children mobile sidebar sample"
    url = "/third-parent/"
    weight = 7
    parent = "examples"

[[main]]
    name = "Custom Jumbotron"
    url = "/custom-jumbotron/"
    weight = 8
    parent = "examples"

[[main]]
    name = "Coming Soon"
    url = "/coming-soon/"
    weight = 10
    parent = "examples"

[[main]]
    name = "Components"
    url = "/components/"
    weight = 3
    identifier = "components"

[[main]]
    name = "Solstice Additions"
    url = "/components/#solstice"
    weight = 1
    parent = "components"
    identifier = "solstice"

[[main]]
    name = "Events Framework"
    url = "/components/#events-framework"
    weight = 2
    parent = "components"
    identifier = "events"

[[main]]
    name = "Dynamic Content"
    url = "/components/#dynamic"
    weight = 3
    parent = "components"
    identifier = "dynamic"

[[main]]
    name = "Deprecated"
    url = "/components/#deprecated"
    weight = 4
    parent = "components"
    identifier = "deprecated"

[[main]]
    name = "Meeting Minutes"
    url = "/components/meeting_minutes/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Membership"
    url = "/components/members/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Taxonomy list"
    url = "/components/taxonomy_list/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Testimonials"
    url = "/components/testimonials/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "YouTube videos"
    url = "/components/youtube/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "FAQ"
    url = "/components/faq/"
    weight = 4
    parent = "solstice"

[[main]]
    name = "Hubspot Contact Form"
    url = "/components/hubspot/"
    weight = 5
    parent = "solstice"

[[main]]
    name = "Featured Footer"
    url = "/components/featured_footer/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Featured Story"
    url = "/components/featured_story/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "HTML Tables"
    url = "/components/tables/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Text Target"
    url = "/components/text_target/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Twitter Timeline"
    url = "/components/twitter_timeline/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Twitter Buttons"
    url = "/components/twitter_button/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Video List"
    url = "/components/video_list"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Adopters"
    url = "/components/adopters"
    weight = 3
    parent = "solstice"

[[main]]
    name = "RSS Feed"
    url = "/components/rss/"
    weight = 3
    parent = "dynamic"

[[main]]
    name = "Users Display"
    url = "/components/user_display/"
    weight = 3
    parent = "events"

[[main]]
    name = "User Bios"
    url = "/components/user_bios/"
    weight = 3
    parent = "events"

[[main]]
    name = "Registration"
    url = "/components/registration/"
    weight = 3
    parent = "events"

[[main]]
    name = "Agenda"
    url = "/components/agenda/"
    weight = 3
    parent = "events"

[[main]]
    name = "Newsroom News"
    url = "/components/newsroom/news/"
    weight = 3
    parent = "dynamic"

[[main]]
    name = "Newsroom Events"
    url = "/components/newsroom/events/"
    weight = 3
    parent = "dynamic"

[[main]]
    name = "Newsroom Resources"
    url = "/components/newsroom/resources/"
    weight = 3
    parent = "dynamic"

[[main]]
    name = "News"
    url = "/components/news/"
    weight = 2
    parent = "deprecated"

[[main]]
    name = "Events"
    url = "/components/events/"
    weight = 3
    parent = "deprecated"

[[sidebar]]
    name = "Hugo Solstice Theme"
    url = "/"
    weight = 3
    identifier = "home"

[[sidebar]]
    name = "Component list"
    url = "/components/"
    weight = 1
    parent = "home"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "component-list"

[[sidebar]]
    name = "GitHub repository"
    url = "https://gitlab.eclipse.org/eclipsefdn/it/webdev/hugo-solstice-theme"
    weight = 2
    parent = "home"
    pre = "<i class=\"fa fa-github fa-fw\"></i>"

[[sidebar]]
    name = "Translation Guide"
    url = "/translations/"
    weight = 3
    parent = "home"
    identifier = "translation-guide"

[[sidebar]]
    name = "Translation Guide 1"
    url = "/translations/"
    weight = 1
    parent = "translation-guide"

[[sidebar]]
    name = "Translation Guide 2"
    url = "/translations/"
    weight = 1
    parent = "translation-guide"

[[sidebar]]
    name = "Third parent"
    url = "/third-parent/"
    weight = 2
    pre = "<i class=\"sidebar-menu-icon\" data-feather=\"github\"></i>"
    identifier = "third-parent"

[[sidebar]]
    name = "Test Children"
    url = "/third-parent/test-children/"
    weight = 1
    parent = "third-parent"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "test-children"

[[sidebar]]
    name = "Test Children 2"
    url = "/third-parent/test-children-2/"
    weight = 1
    parent = "third-parent"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "test-children-2"

[[sidebar]]
    name = "Test Children Children 1"
    url = "/third-parent/test-children/test-children-children/"
    weight = 1
    parent = "test-children"

[[sidebar]]
    name = "Test Children Children 2"
    url = "/third-parent/test-children/test-children-children-2/"
    weight = 2
    parent = "test-children"

[[sidebar]]
    name = "Membership"
    url = "#"
    weight = 4
    identifier = "membership"

[[sidebar]]
    name = "Sidebar Item 1"
    url = "#"
    weight = 2
    parent = "membership"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"

[[main_menu_demo]]
    identifier = "custom-menu"
    name = "Custom Menu"
    weight = 1

[[main_menu_demo]]
    parent = "custom-menu"
    name = "Go Home"
    url = "/"
    weight = 1

# Custom sidebar
[[sidebar]]
  identifier = "sidebar-custom"
  name = "Eclipse Working Groups"
  url = "https://www.eclipse.org/collaborations/"
  weight = 1

[[sidebar]]
  parent = "sidebar-custom"
  name = "Explore Working Groups"
  weight = 1
  url = "https://www.eclipse.org/org/working-groups/explore/"

[[sidebar]]
  parent = "sidebar-custom"
  name = "About Working Groups"
  weight = 2
  url = "https://www.eclipse.org/org/working-groups/about/"

[[sidebar]]
  identifier = "sidebar-additional"
  name = "Related Links"
  weight = 2

[[sidebar]]
  parent = "sidebar-additional"
  name = "Working Group Process"
  weight = 1
  url = "https://www.eclipse.org/org/working-groups/process/"

[[sidebar]]
  parent = "sidebar-additional"
  name = "Working Group Operations"
  weight = 2
  url = "https://www.eclipse.org/org/working-groups/operations/"

[[sidebar]]
  parent = "sidebar-additional"
  name = "Working Group Development Effort Guidelines"
  weight = 3
  url = "https://www.eclipse.org/org/working-groups/wgfi-program/"